import React from 'react';

import FancyHeader from '../components/FancyHeader';
import styles from './About.scss';

export default function About() {
  return (
    <React.Fragment>
      <div className={styles.header}>
        <FancyHeader label="How to Use" width="500px" />
      </div>
      <div>
        <h2>Form</h2>
        <p>- All fields are required</p>
        <p>- Validation messages will be shown</p>
        <p>- Created at date is automatically generated by the application when a new record is submitted</p>
        <p>- After submitting a valid record it will be automatically displayed in the table below</p>

        <h2>User Table</h2>
        <p>- Contains a search field used to filter the table items by the User Name</p>
        <p>- If a search parameter is not provided all records will be shown</p>
        <p>- If a search parameter doesn't return any results the state of the table will not change</p>
      </div>
    </React.Fragment>
  );
}
